// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzlwEsrwGKrk7tBGMP4NBW8FidK0w-huQ',
    appId: '1:298873030090:web:9591e24e49640b7e783b33',
    messagingSenderId: '298873030090',
    projectId: 'my-mcommerceapp-2024',
    authDomain: 'my-mcommerceapp-2024.firebaseapp.com',
    storageBucket: 'my-mcommerceapp-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB-l5r4ZBrxinIM8N6DcGR57i5Gc_R2Jc',
    appId: '1:298873030090:android:fd275b272b3ae3df783b33',
    messagingSenderId: '298873030090',
    projectId: 'my-mcommerceapp-2024',
    storageBucket: 'my-mcommerceapp-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9LS21PVMOW8Pg3DA_S-hn6FRcq5HU2kU',
    appId: '1:298873030090:ios:75056979840382c9783b33',
    messagingSenderId: '298873030090',
    projectId: 'my-mcommerceapp-2024',
    storageBucket: 'my-mcommerceapp-2024.appspot.com',
    androidClientId:
        '298873030090-3ot290ovr45aqoiejqgnpgbr09013q0h.apps.googleusercontent.com',
    iosClientId:
        '298873030090-mfbnjtp2cktf9j15t3jdffui0iml62hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesApp',
  );
}
